name: Cargo Build & Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            components: rustfmt, clippy

      - run: cargo fmt --all -- --check
      - run: cargo build --verbose
      - run: cargo clippy --all-features
      - run: cargo test --verbose
